				document.writeln("<div class='select-up'>");
					document.writeln("<div class='select-left'>");
						document.writeln("<div class='select-city'>");
							document.writeln("<b>城市</b>");
							document.writeln("<input type='text'>");
						document.writeln("</div>");
						document.writeln("<div class='select-age'>");
							document.writeln("<b>年龄段</b>");
							document.writeln("<input type='text'>");
						document.writeln("</div>");
					document.writeln("</div>");
					document.writeln("<a href='#' class='select-reset-btn'>重置</a>");
				document.writeln("</div>");
				document.writeln("<div class='select-down'>");
					document.writeln("<div class='select-left'>");
						document.writeln("<div class='select-sex'>");
							document.writeln("<b>性别</b>");
							document.writeln("<div class='checkbox-new' id='checkbox-new'>");
								document.writeln("<span>male</span>");
							document.writeln("</div>");
							document.writeln("<div class='checkbox-new' id='checkbox-new'>");
								document.writeln("<span>female</span>");
							document.writeln("</div>");
							document.writeln("<div class='checkbox-new' id='checkbox-new'>");
								document.writeln("<span>unknown</span>");
							document.writeln("</div>");
						document.writeln("</div>");
						document.writeln("<div class='select-health'>");
							document.writeln("<b>健康状况</b>");
							document.writeln("<div class='checkbox-new' id='checkbox-new'>");
								document.writeln("<span>健康</span>");
							document.writeln("</div>");
							document.writeln("<div class='checkbox-new' id='checkbox-new'>");
								document.writeln("<span>一般</span>");
							document.writeln("</div>");
							document.writeln("<div class='checkbox-new' id='checkbox-new'>");
								document.writeln("<span>较弱</span>");
							document.writeln("</div>");
							document.writeln("<div class='checkbox-new' id='checkbox-new'>");
								document.writeln("<span>小疾</span>");
							document.writeln("</div>");
							document.writeln("<div class='checkbox-new' id='checkbox-new'>");
								document.writeln("<span>残疾</span>");
							document.writeln("</div>");
						document.writeln("</div>");
					document.writeln("</div>");
					document.writeln("<a href='#' class='select-search-btn'>搜索</a>");
				document.writeln("</div>");